model: yolov5x-cls.pt
data: .
epochs: 50
batch_size: 64
imgsz: 256
nosave: false
cache: null
device: ''
workers: 8
project: yolov5-code/runs/train-cls
name: exp-1
exist_ok: true
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 33
local_rank: -1
save_dir: yolov5-code/runs/train-cls/exp-1
